services:
  - type: web
    name: snake-spectacle
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-db
          property: connectionString
    autoDeploy: false

databases:
  - name: snake-db
    plan: free
    databaseName: snake_db
